### ISSUE TITLE
Don't use microbenchmarks

### ISSUE THREAD

**Issue by mdibaiee** [loverajoel/jstips#10]
Hey,

I highly suggest you read these: 

http://mrale.ph/blog/2014/02/23/the-black-cat-of-microbenchmarks.html
http://mrale.ph/blog/2012/12/15/microbenchmarks-fairy-tale.html
http://jsperf.com/string-concat-fast/9#comment-1

Most of those microbenchmarks are illusions, I suggest you shift from those performance tips killing code readability to some actually useful tips, I really like the idea of repository :+1:, but not like this.

To my understanding, this microbenchmark is an illusion:

``` javascript
var arr = [1,2,3,4,5];

arr.unshift(0);
[0].concat(arr); // 98% faster in Chrome 47.0.2526.106 on Mac OS X 10.11.1
```

Why? because `[0].concat(arr)` is generating a new array which is not used, so the VM doesn't run it at all! That's why it's _98 percent_ faster, because it's not running anything. Most probably if you are using this in some real-life example, they run at the same speed.

JavaScript engines are too smart to require us to use such tricks in order to make them run fast, these tricks just making our code hard to understand.

**Comment by mamal72** [comment]
Hey,
Well, I agree with @mdibaiee too. I like readable code more than some weird fast code.
I think these parts of performance stuff and optimizations should be done inside the JS engines. :+1:

**Comment by GantMan** [comment]
ALSO: Tips like this do not account for future.  Even if you were 100% right (and agreed the VM means you're not with a mircotest), versions + environment changes means that you're adding a death sentence to your JS tip.  It's better to create tips that will stand the whole year and enrich your repo as it grows.

**Comment by connor4312** [comment]
> JavaScript engines are too smart to require us to use such tricks in order to make them run fast

This. Sometimes, hacks may be faster. But engines strive to make the _correct_ way faster--that's what they're optimizing for. In the long run, as engines improve, hacks will inevitably end up being slower while reducing the readability/maintainability of your code.

**Comment by loverajoel** [comment]
Hey guys, I understand what you are saying and yes, maybe was a bad tip to start.
The tips will not be always about performance, but thanks for your suggestion I will take care for the future.
@mdibaiee good articles, you are 100% right.

This kind of comments are very usefull and I'm thinking of link this issue with the tip.

I invite you to send some tip and help the community write better code!

Thanks guys

**Comment by BenoitZugmeyer** [comment]
> Why? because `[0].concat(arr)` is generating a new array which is not used, so the VM doesn't run it at all! That's why it's 98 percent faster, because it's not running anything. Most probably if you are using this in some real-life example, they run at the same speed.

It may have a small impact, but the real issue is: the [two benchmark cases](http://jsperf.com/unshift-item-inside-an-array) are not doing the same thing. The `setup()` function initializing the array is called once at the beginning, then the cases are run thousands of times. The `unshift` case is mutating the initial array by prepending 0, causing the initial array to grow each time it is run. Conversely, the `concat` case is not mutating the initial array, so the operation is always done on a very small array, which is way faster.

See [my edition of the benchmark](http://jsperf.com/unshift-item-inside-an-array/4) to have better results. The first case is exactly the same, but the second is changing the initial array in the same way the first one does.

Anyway, I'm not a big fan of microbenchmarks either.

**Comment by mdibaiee** [comment]
@loverajoel Thank you! ✌️ I will add tips as soon as I find some time.

**Comment by mvedie** [comment]
I don't know precisly how jsperf works, but i think it's better if the test method is the following : http://jsperf.com/unshift-item-inside-an-array/11
Each function use a reserved array and the first function doesn't affect the array for the second function.

Tell me if my comment is stupid because i don't know if jsperf run setup in both case ?

**Comment by Petah** [comment]
Also that test is kinda wrong as it is dependant of the size of the array. If you have a large array then `push` is faster: http://jsperf.com/push-item-inside-an-array/7

**Comment by jonathanKingston** [comment]
@loverajoel - [Rounding the fast way](https://github.com/loverajoel/jstips#18---rounding-the-fast-way) is like microseconds in difference at best which is complete microperf and also creates two subtle differences in that it operates on a 32bit address space and also is `Math.ceil(-1.5)` for negative numbers. (**I would completely swap out this tip**)

**Comment by gunar** [comment]
This tip is strongly misleading and should be updated according to the comments above (and @BenoitZugmeyer's edit of the jsperf).

**Comment by FagnerMartinsBrack** [comment]
Microbenchmarks are useless unless you are working developing a new language or framework. If that is the case, then you definitely don't need jstips. This should be about legibility and real life usage, not things that 99% of the JavaScripters will not be using in the wild.

**Comment by kurtextrem** [comment]
imho I find the tip fitting.
JSTips is about stuff that most of us do not know. Who knew, that `~`was doing something useful? Who knew what `~~` does?
I see how other methods are faster and more readable, but as long as there are popular projects out there which use this syntax, it is great to know what it means.

**Comment by jonathanKingston** [comment]
@kurtextrem I don't really disagree with that statement, it would be nicer to clarify to beginners that it isn't a good format for these x reasons. Cool drills you didn't know about come with warning labels too.

**Comment by kurtextrem** [comment]
@jonathanKingston 

> Although ~~ may perform better, for the sake of readability please use Math.floor().

I think that is enough as warning label - or how would you re-paraphrase it?

**Comment by FagnerMartinsBrack** [comment]
<sub>(For the sake of readability I would say that `Math.floor` could be a one-line module called `round-down`, just saying)</sub>

**Comment by jonathanKingston** [comment]
@kurtextrem hmm sure that line wasn't in when it was on the single pager. It is however missing the issue about it not being equivalent either which is the bigger issue.

**Comment by zenopopovici** [comment]
Guys can you make the required changes for the affected tips in a PR?
