### ISSUE TITLE
Organization of the Repo Tip Structure

### ISSUE THREAD

**Issue by pertrai1** [loverajoel/jstips#101]
I have issued a PR #100 that will help to start the formation of a repo that can continue to increase as the tips come in overt the year. My proposal has it where there is a 2016 directory with a README that has a link to each month for the year, and then a directory for each month inside of that directory that has a README for the tips of that month. This will help to keep the README to a minimum for just that month.

**Comment by drakmail** [comment]
Seems very good! I think there a slightly better approach – keep one file per tip in month directory

**Comment by pertrai1** [comment]
@drakmail So you are thinking of having something that would be like so:

```
-- 2016
----january
--------day1.md -- Have commit message snippet type
--------day2.md -- Have commit message snippet type
--------README.md -- Table of contents for January
----february
--------day1.md .......
README.md - Repo overview and high level TOC
```

**Comment by drakmail** [comment]
@pertrai1 as mentioned in #13 it will be nice to have title in filename – it could be easily converted to readable URL format in static site generators like Jekyll

**Comment by pertrai1** [comment]
@drakmail yes I like that method much more.

**Comment by loverajoel** [comment]
Hey guys, we are talking about it in this issue #13.
Now I'm working in a jelly blog and the file organization will be like this 
![image](https://cloud.githubusercontent.com/assets/1700100/12399663/270b5c36-bdfa-11e5-8251-cbbd057b2d54.png)
https://github.com/barryclark/jekyll-now/tree/master/_posts

**Comment by drakmail** [comment]
@loverajoel keeping eye on #13, but @pertrai1 suggested nice idea – doesn't keep all posts in just flat `_posts` directory, but keep it in structured sub-directories by months and years. Maybe, then move it in #13 and close this issue as duplicate?

**Comment by loverajoel** [comment]
@drakmail yes, it's a good idea but I'm not sure if jelly allow me this organisation, I have to check it

**Comment by drakmail** [comment]
If you are talking about [jekyll](https://jekyllrb.com) then yes, it allow usage of nested directory structure

**Comment by loverajoel** [comment]
@drakmail yes, sorry! Awesome it's a deal!

**Comment by rwoll** [comment]
I've made PR #108 which includes a `_posts` directory whose files are ready to be used with a static site generator like jekyll. There is also a template file in `_drafts` of the PR that shows the file I used to generate the posts.

**Comment by loverajoel** [comment]
@rwoll awesome!!! I think that this week I can end the theme and create the blog, thanks

**Comment by drakmail** [comment]
@loverajoel when you done you could use js2016.tips domain if you will use gh-pages branch, just let me know

**Comment by pertrai1** [comment]
@loverajoel @drakmail @rwoll This is great. Let me know if there is any help needed with getting Jekyll up and running with gh-pages.

**Comment by loverajoel** [comment]
Hey finally the repo change the format, now the `master` branch is `gh-page` and it's live in jstips.co.

Feedback and suggestion are welcome
