### ISSUE TITLE
#12 - Pseudomentatory parameters in ES6 functions #ES6

### ISSUE THREAD

**Issue by gihrig** [loverajoel/jstips#109]
Is  Pseudomentatory even a word? What does this mean?

I think the author meant pseudo-mandatory parameters?

**Comment by module17** [comment]
@gihrig It stems from the word `mentation`, meaning `mental activity; the result of`.

**Comment by gihrig** [comment]
That doesn't fit the usage in the tip, making function parameters required, does it?
