### ISSUE TITLE
Descent Order for Everyday Tip 

### ISSUE THREAD

**Issue by ghost** [loverajoel/jstips#11]
```

## Tip 99
balabala...

...

## Tip 02

balabala...

## Tip 01

balabala...

```

Otherwise, we may have to scroll to the end of the page in order to find the latest tip.

**Comment by FlorianBELLAZOUZ** [comment]
:+1:

**Comment by CodeBrauer** [comment]
:+1:

**Comment by loverajoel** [comment]
@li-xinyang yes this is a good catch, I will change the order! Thanks for the suggestion.

**Comment by loverajoel** [comment]
Done https://github.com/loverajoel/jstips/commit/7b6229b985340ad9619be2fc7c1cd3bc4f35f4e6
