### ISSUE TITLE
Split tips into several .md files

### ISSUE THREAD

**Issue by AvraamMavridis** [loverajoel/jstips#121]
Since the README.md starts getting longer it would be nice to split the tips into several files, and has only a list of titles on the README.md with links to the tip's md file. It will make the reading easier and also people will have less conflicts since the will work in different files and not on the README.

**Comment by drakmail** [comment]
Duplicates #13 :)

**Comment by loverajoel** [comment]
closed by duplicate

**Comment by AvraamMavridis** [comment]
:+1:
