### ISSUE TITLE
Tips for Security.

### ISSUE THREAD

**Issue by jknaresh** [loverajoel/jstips#123]
Any Security Issue and Solution?

**Comment by loverajoel** [comment]
This would be great! +1

**Comment by jonathanKingston** [comment]
Happy to contribute a few:
- [ ] [Web crypto](https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto)
- [ ] [Secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)
- [ ] [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)
- [ ] [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)

All of these impact JavaScript however not sure on if any but web crypto fit the current format. Other generic ones may be more relevant like basic security principles like filtering data in node may be more relevant.

**Comment by jknaresh** [comment]
Is any way, can we secure AJAX request?

**Comment by jonathanKingston** [comment]
@jknaresh well AJAX is 'secure' out of the box but it depends on what you are referring to. For example you can't just make an AJAX request to another server without both parties opting into using a **[CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)** request, this means that hacker sites can't steal your GeoCities session just by making an AJAX request.

Now the security mentioned above is Same-Origin Policy(**[SOP](https://en.wikipedia.org/wiki/Same_origin_policy)**) which prevents an untrusted Origin speaking to another Origin from doing things you didn't expect with it. Forms and links can cross Origins but they can't read or execute the code on the other origin. (Origin is just a fancy name for Hostname, Port and Protocol _So https://example.com can't speak to http://example.com._)

So I assume you are more on about how to secure a conversation between your users and the server itself?
Most of the security features actually need to come from your server:
- [HPKP](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning)
- [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy)
- [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
- [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security)

One exception is [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) token protection which usually requires some setup on the client side to enable. It prevents the user sending requests they didn't expect from their own browser. This can happen as any Origin can POST a form to another, meaning a user can be on example.com and end up deleting their Habbo Hotel account as the hacker has sent a form over to Habbo which you are logged into.

Essentially CSRF tokens work by using code that can only be read by users on the page to prevent privileged requests from happening. This is similar to Cookies in that it is sent back to the server on the request however it's different as it's usually sent in a HTTP header by code that recognises the page has loaded and the user actually made that action.
This comes as a pain for AJAX requests as it usually means taking server response headers and injecting it into your AJAX request headers to give a unique key back to the server.

Other than that you could use [WebCrypto](https://developer.mozilla.org/en-US/docs/MDN/Doc_status/API/WebCrypto) to store the data of your users on your servers encrypted without you even having the keys.

This was a little hastily written but yeah, let me know what sort of thing you are after securing and I can expand on that.

**Comment by zenopopovici** [comment]
Hey guys,

Maybe we can muster a few examples, and good case practices in a PR :see_no_evil: from some of you who have a bit of experience with this?

**Comment by jonathanKingston** [comment]
Yeah will get some commits up soon. Can't guarantee timeline at the moment.
Is there any preference in the order of the work for the comments I left
above?
Are there other topics or things that might be out of scope?

**Comment by zenopopovici** [comment]
There are no restrictions, and we don't know where to start so I guess anything that is useful would do. I would start with best practices and small but smart stuff that helps in securing a JS proiect. E.g.: Crypto is pretty advanced stuff, so I would not prioritize this.

**Comment by jonathanKingston** [comment]
@zenopopovici sure crypto doesn't really make sense as a tip despite perhaps hashing examples which are far less technical.
The other topics I mentioned are not really simple tips that could be copy and pasted etc. SRI probably is the only simple suitable for a tip where a few lines of code can demo how to prevent against hijacked servers.

**Comment by zenopopovici** [comment]
Well we shouldn't do it just for the sake of it. If we can come up with short tips on Security, then please submit a pr, if not, then maybe it doesn't fit the purpose of jstips.
