### ISSUE TITLE
tip #21 shuffle-an-array ~ alternative implementation contains invalid `this`

### ISSUE THREAD

**Issue by dfkaye** [loverajoel/jstips#136]
In tip https://github.com/loverajoel/jstips/blob/master/README.md#21---shuffle-an-array, the alternate shuffle function by @mvedie ( which I really like, btw) appears to assume that `shuffle` is defined on the `Array.prototype` as it contains a `slice()` method on `this`, rather than on an `array` parameter ~ but that throws an error:

```
function shuffle() {
    return this.slice(0).sort(function() {
        return 0.5 - Math.random();
    });
};

shuffle([1,2,3,3,4,5,6]);
// TypeError: this.slice is not a function
```

Fix that by specifying `array` as a parameter, and calling `slice()` on that instead:

```
function shuffle(array) {
  return array.slice().sort(function() {
    return 0.5 - Math.random();
  });
};

shuffle([1,2,3,3,4,5,6]);
// (e.g.) [3, 1, 2, 3, 5, 4, 6]
```

**Comment by loverajoel** [comment]
@0xmtn ping

**Comment by 0xmtn** [comment]
Fixed - https://github.com/loverajoel/jstips/pull/137
