### ISSUE TITLE
The naive shuffling algorithm does not work

### ISSUE THREAD

**Issue by AlexanderZeilmann** [loverajoel/jstips#140]
I am talking about the algorithm about the following algorithm by @mvedie:

``` js
function shuffle(array) {
    return array.slice(0).sort(function() {
        return 0.5 - Math.random();
    });
};
```

Information why this algorithm does not work (and shouldn't be used) can be found for example in [this awesome blog post](http://bost.ocks.org/mike/algorithms/#shuffling) and by googling a bit.

I'm therefore proposing to remove the corresponding section from the tip.

**Comment by mvedie** [comment]
Ok, my bad, thank you for this link which opened my eyes.

**Comment by AlexanderZeilmann** [comment]
No worries @mvedie, I'm here to help :-D

**Comment by loverajoel** [comment]
@alawatthe hahah :+1:

**Comment by mvedie** [comment]
And i'm here to learn :)
