### ISSUE TITLE
Best way to minify JS with secure?

### ISSUE THREAD

**Issue by jknaresh** [loverajoel/jstips#142]
I could not find proper minify compliers for JS minify? Can any one suggest?

**Comment by infacq** [comment]
gulp or bower is not enough?

**Comment by rjgotten** [comment]
> gulp or bower is not enough?

Gulp is a task-runner and bower is a package manager. Neither is a minifier.

You want a decent minifier, you use something like UglifyJS.

**Comment by xovel** [comment]
[**UglifyJS2**](https://github.com/mishoo/UglifyJS2) is a good choice

> It’s almost a full rewrite (except for the parser which is heavily modified, everything else starts from scratch).

**Comment by indianakernick** [comment]
Yeah UglifyJS is what I use. 👍🏼
