### ISSUE TITLE
tips #19 - add little trick

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [loverajoel/jstips#143]
Thank for the tips.

We can also use this trick to do a safe string concatenation :

``` js
var one = 1;
var two = 2;
var three = '3';

var result = '' + one + two + three; // "123"
```

it's less verbose and faster !

http://jsperf.com/string-concatenate-concat-vs-join/4

**Comment by gogainda** [comment]
@FlorianBELLAZOUZ  nice trick

**Comment by kurtextrem** [comment]
I'd say this one should probably replace the `.concat` function in #19.

**Comment by yuvarajvemula** [comment]
Nice tip @FlorianBELLAZOUZ    :thumbsup:

**we can also make use of [`template strings`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) to acomplish the same..**

``` javascript
var one = 1;
var two = 2;
var three = 3;

var result = ` ${one}${two}${three} `;  // "123"

// less error prone

```

_See_ [Template Strings at Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings)
