### ISSUE TITLE
builds static pages of these tips is allowed?

### ISSUE THREAD

**Issue by hingsir** [loverajoel/jstips#146]
[https://hingsir.github.io/jstips-site/dist/tips/](https://hingsir.github.io/jstips-site/dist/tips/)

**Comment by loverajoel** [comment]
@hingsir I'm working in a jekyll-now theme and I think that this weekend will be ready

**Comment by hingsir** [comment]
@loverajoel looking forward to !

**Comment by lockys** [comment]
I build a site called `awesome search` providing simple functionality to search in awesome list recently with a friend.
As `jstips` is listed in awesome list, so `jstips` is in `awesome search` automatically.
https://awesomelists.top/#/repos/loverajoel/jstips :)
Just let users overview the tips by the category dropdown.
I think it will be better to see the official static site of `jstips` by @loverajoel.
repo:
https://github.com/lockys/awesome-search/

**Comment by hingsir** [comment]
@lockys +1

**Comment by loverajoel** [comment]
@hingsir @lockys hey I added those [here](https://github.com/loverajoel/jstips#lets-keep-in-touch) and you can see the blog live in jstips.co

Thanks

**Comment by lockys** [comment]
@loverajoel  that's fantastic! :100:
