### ISSUE TITLE
Tip #23 is the slowest on firefox

### ISSUE THREAD

**Issue by windows1087** [loverajoel/jstips#149]
Firefox 43.0.4 on Mac

http://i.imgur.com/1W51hsJ.png

**Comment by marklabenski** [comment]
![bildschirmfoto 2016-01-23 um 17 44 10](https://cloud.githubusercontent.com/assets/1036749/12531370/f7a5c6f4-c1f8-11e5-8c0b-e50996fa264d.jpg)

It's also one of the slowest in Safari Version 9.0.3 (11601.4.4) on Mac OS X El Capitan

_(edit) All 3 major browsers (Chrome, Safari, Firefox at latest versions) on my MacBook 13' retina late 2013 on Mac OS X El Capitan compared, the fastest ways are Bitwise operators._

**Comment by rjgotten** [comment]
The `parseInt` function shouldn't even be on that list. It doesn't perform proper value conversion to the number type; it parses strings - and only strings! - into numbers.

E.g.

``` js
parseInt(new Date(2016,1,1),10) // NaN
Number(new Date(2016,1,1)) // 1454281200000
```

On top of that, it parses _partially accepted_ strings, which is generally **not** what you want when you're performing type conversion.

E.g.

``` js
parseInt("1F",10) // 1
Number("1F") // NaN
```

**Comment by indianakernick** [comment]
@rjgotten 👍🏼

**Comment by marklabenski** [comment]
Thank you @rjgotten 
But the point was, that it strongly depends on the browser/system wether the suggested method is the fastest. So it shouldn't be called "the fastest way" in general (Even if I wish it was)
