### ISSUE TITLE
How can I follow just the tips?

### ISSUE THREAD

**Issue by rschindlauer** [loverajoel/jstips#15]
I am watching the repo, which means I get all issues, comments, and PRs. I'd like to just follow the tips themselves, is there any way (without Twitter)?

**Comment by Shahor** [comment]
:+1:

**Comment by bbultman** [comment]
Seconded!

**Comment by loverajoel** [comment]
@rschindlauer not by the moment, in this issue https://github.com/loverajoel/jstips/issues/13 we are talking about to migrate this repo to jekyll blog and by this way you can follow the rss feed

**Comment by rocketinventor** [comment]
@loverajoel By "migrate" do you mean adding a branch?

**Comment by kurtextrem** [comment]
Most tips come in via pull request, so simply "Watch" and turn on e-mail notifications :D

**Comment by mhulse** [comment]
Not sure if this would be of any help, but I created a repo that uses Jekyll and GitHub to generate just an XML feed:

https://github.com/mhulse/bookmark-utils

The feed is updated via the yaml file in the _data folder. 

My plan was to keep the feed updated via [Prose](http://prose.io).

**Comment by drakmail** [comment]
You could get tips [by email](http://js2016.tips)

**Comment by mhulse** [comment]
> You could get tips by email

Loving the newsletter. Thanks!

**Comment by loverajoel** [comment]
Hey good news, now you can follow this [official rss](http://www.jstips.co/feed.xml)

**Comment by rschindlauer** [comment]
Cool, thanks! Closing this as resolved.

**Comment by rishantagarwal** [comment]
You might soon see an IOS App for it .

**Comment by mhulse** [comment]
Quick question, what site is official? jstips.co or js2016.tips?

**Comment by drakmail** [comment]
jstips.co is based on gh-pages branch of this repo, js2016.tips – mostly is just a email subscription form maintained by me :)

**Comment by mhulse** [comment]
> jstips.co is based on gh-pages branch of this repo, js2016.tips – mostly is just a email subscription form maintained by me :)

Ah, cool! Thanks for setting up the email sub! It's a perfect read in my inbox every day. Formatted very well and quick to grok. :+1:

**Comment by drakmail** [comment]
Thank you!
