### ISSUE TITLE
ISO 8601 Date Standardization

### ISSUE THREAD

**Issue by jnovack** [loverajoel/jstips#17]
I propose use of the ISO 8601 Date format (_e.g. 2016-01-03 for January 3rd, 2016_)

https://en.wikipedia.org/wiki/ISO_8601

**Relevant XKCD**
![Relevant XKCD](https://imgs.xkcd.com/comics/iso_8601.png)

**Exhibit A**, https://github.com/loverajoel/jstips/blob/cc8584a7f5812ac7d34f483c9269f846dad35169/README.md

```
#03 - Improve Nested Conditionals
01/03/2016 by AlbertoFuente
```

**Exhibit B**, https://github.com/loverajoel/jstips/blob/cc8584a7f5812ac7d34f483c9269f846dad35169/README.md

```
#02 - ReactJs - Keys in children components are important
02/01/2016 by @loverajoel
```

**Comment by loverajoel** [comment]
I agree with you! Do you wanna make a PR for solve this? thanks for your suggestion!

**Comment by mvedie** [comment]
This issue can be closed ;)
