### ISSUE TITLE
why doesn't it update as usual today？

### ISSUE THREAD

**Issue by cococe** [loverajoel/jstips#179]
~~偶尔从论坛上发现了这个项目，每天早晨上班之前看一看，今天怎么没有更新？~~
I found this project from the forum by accident and always look through it before  going to work every morning，but why doesn't it update as usual today？

**Comment by hueitan** [comment]
You should <s>replied</s>reply in English.

**Comment by cococe** [comment]
@huei90 ok。
 You should `reply` in English

**Comment by hueitan** [comment]
thank you @cococe

**Comment by lockys** [comment]
The title should be updated as well.
Maybe you should consider the place where the owner lives.
He is in Spain (UTC + 1) I think, I guess the time in Spain is about 1/27 9:00 a.m now
You filed this issue at 1/27 3:00 a.m in Spain. It's time for sleep. :grin:

**Comment by cococe** [comment]
@lockys thank you.
