### ISSUE TITLE
add link to jsbin with tip's code

### ISSUE THREAD

**Issue by qaraluch** [loverajoel/jstips#186]
Would be nice to play with tip's code to grasp the topic better, wouldn't it?

**Comment by dan-relvas** [comment]
I agree, this sounds pretty cool.

**Comment by drakmail** [comment]
:+1:

**Comment by kurtextrem** [comment]
I think Babel (online) is better (ES6, console.log output)

**Comment by loverajoel** [comment]
hey add you idea [here](https://github.com/loverajoel/jstips/issues/251)

**Comment by gcjbr** [comment]
I second that

:+1:

**Comment by zenopopovici** [comment]
:+1: Great idea

**Comment by zenopopovici** [comment]
Moved to https://github.com/loverajoel/jstips/issues/368.
If you guys want to help let me know.
