### ISSUE TITLE
recursive functions with memoization caching example issue

### ISSUE THREAD

**Issue by danieluhl** [loverajoel/jstips#193]
@loverajoel Either I'm entirely missing something or this first example doesn't do anything:
https://github.com/loverajoel/jstips/blob/gh-pages/_posts/en/2016-01-29-speed-up-recursive-functions-with-memoization.md

```
var fibonacci = (function(){
    var cache = {
        0: 0,
        1: 1
    };
    return function(n){
        return n <= 1 ? cache[n] : (cache[n] = cache[n-1] + cache[n-2]);
    }
})()
```

I think what this might be going for is something like this?

```
var fibonacci = (function() {
  cache = {
    '0': 0,
    '1': 1
  };

  function f(n) {
    var result;
    if (n in cache) {
      result = cache[n];
    } else {
      result = f(n - 2) + f(n - 1);
      cache[n] = result;
    }
    return result;
  }
  return f;
})();
```

**Comment by loverajoel** [comment]
@hingsir ping

**Comment by mrosata** [comment]
@danieluhl true

**Comment by RafaelTaranto** [comment]
Yep, the first example only works if you go sequentially starting at 2.

**Comment by ffigiel** [comment]
This will be fixed in es9.
jk, thanks for pointing this out :+1:

**Comment by hingsir** [comment]
my bad, [pr196](https://github.com/loverajoel/jstips/pull/196/files) may fix that

**Comment by loverajoel** [comment]
@danieluhl PR merged, can I close this?

**Comment by RafaelTaranto** [comment]
Still not getting result from cache, can't submit pr right now but the return should be :

`return (n in cache) ? cache[n] : (cache[n] = self(n-1) + self(n-2));`
