### ISSUE TITLE
Tip #29 Fibonacci example incorrect

### ISSUE THREAD

**Issue by tommot348** [loverajoel/jstips#195]
the (cache[n]=cache[n-1]+cache[n-2]) part can't work, because the values arent't computed first if you don't call the function for every number smaller than the one you want.

this works:
var fibonacci = (function(){
    var cache = {
        0: 0,
        1: 1
    };
    return function(n){
        return n <= 1 ? cache[n] : (cache[n] = (cache[n-1] || fibonacci(n-1) + cache[n-2] || fibonacci(n-2)));
    }
})();

**Comment by loverajoel** [comment]
@hingsir ping

**Comment by hingsir** [comment]
thanks, see [pr196](https://github.com/loverajoel/jstips/pull/196/files)

**Comment by sylvaindethier** [comment]
Are you sure of that implementation ?
I've benchmarked this tips, but it seems memoized functions takes longer to run, if it can run !

Check out the bencmarks:
- jsPerf: https://jsperf.com/js-tips-29
- jsBin: https://jsbin.com/silobu/edit?js,console

I propose a better cached version for fibonacci, which can be simply implemented for any other recursive function:

``` javascript
// Better cached fibonacci
var fibonacci = (function() {
  var cache = {0: 0, 1: 1};
  // do not interfer w/ global fibonacci if any
  return function fibonacci_(n) {
    if (!(n in cache)) cache[n] = fibonacci_(n-1) + fibonacci_(n-2);
    return n < 2 ? n : cache[n];
  };
}());
```

**Comment by tommot348** [comment]
I added some stuff
- [jsperf](http://jsperf.com/js-tips-29/2)
- [jsbin](https://jsbin.com/qobelopaje/edit?js,console)

The iterative version is to show that tail recursive functions can (always) be written in an iterative way and that's almost always faster.

**Comment by zenopopovici** [comment]
@sylvaindethier Please make a PR and then we can review it.

**Comment by sylvaindethier** [comment]
@zenopopovici sure, should have done it first.
Question: Do I have to update both [_posts/en](tree/gh-pages/_posts/en) & [_posts/zh_CN](tree/gh-pages/_posts/zh_CN) corresponding files ?
If I'm totally wrong, what should I have to do ?

**Comment by zenopopovici** [comment]
@sylvaindethier Yes, please update both posts if you can, if not, we have to involve @sjfkai for the chinese version.

In the coming days we'll add new rules and submit every update / new tip to a review by the community if it's approved, it will get merged. See #251

**Comment by sylvaindethier** [comment]
@tommot348 Nice perf for your iterfib algo dude :+1: . I'm working on a PR and will include your algos w/ your permission.
@zenopopovici But the initial point is that the `memoized` functions (fibonnacci and others) are very poor in performance compared w/ standard algo. The point was: are you sure of the implementation, or the point that memoized funcs are more efficient ?

**Comment by sylvaindethier** [comment]
@zenopopovici I'm working on that PR. But the changes are from @tommot348, code has better [perf](https://jsperf.com/js-tips-29/2) than mine.

**Comment by zenopopovici** [comment]
@sylvaindethier I see now, maybe the tip is not really OK and we have to change it completely. That's why we're implementing tips review. 
@loverajoel weigh in on this?

**Comment by zenopopovici** [comment]
PR is #264

**Comment by sjfkai** [comment]
Usually, Before I translate the new tip, I will review new commits to update every changes in `en` tips. 

But if you can update both language I would really appreciate

**Comment by sylvaindethier** [comment]
@sjfkai done! If the text has no explanation about the code the PR #264 should be OK

**Comment by tommot348** [comment]
@sylvaindethier you can use my code. Thanks for looking at it again

**Comment by pastrop** [comment]
As we all know this is a pretty classic problem. Below is Douglas Crockford code for that (Chapter 4 from the JS the Good Parts):

``` js
var fibonacci = function ( ) {
 var memo = [0, 1];
 var fib = function (n) {
 var result = memo[n];
 if (typeof result !== 'number') {
 result = fib(n - 1) + fib(n - 2);
 memo[n] = result;
 }
 return result;
 };
 return fib;
}( );
```

So here is a thought: Except the author submitting the tip truly believes that submitted solution is significantly better than whatever else has been done before, I don't think such a tip has a merit.  Again, I am talking about well researched problems.  Other examples that come to mind are: Tail call optimization for the factorial function or using closures inside the loop.  I suggest we should close this item.  For the future, we need to decide how to deal with this sort of tips.  In my mind there are 2 ways ( again assuming it doesn't include a truly innovative approach): It either should be shipped including a generally accepted solution (i.e. something widely published in the literature or posted on stackoverflow with hundreds of votes) or it doesn't get shipped.  Just my 2 cents....
