### ISSUE TITLE
Convert-to-Boolean tip of questionable value

### ISSUE THREAD

**Issue by boneskull** [loverajoel/jstips#197]
`!!value` converts `value` to a `Boolean`. This much is true. 

It's also arguably "too clever" and a source of confusion to inexperienced JS programmers--it's in the same category as using `~` with `Array.prototype.indexOf()`. 

An alternative which I have found to be much more obvious (though perhaps too verbose for some) is instead using `Boolean(value)`, which does the same. 

Just wanted to start a conversation around this. I think this project is a good idea, but it's my hope the tips will show great ways to solve problems instead of just ways to solve problems in the fewest amount of characters.

**Comment by loverajoel** [comment]
@hakhag ping!

@boneskull maybe you can move this conversation to http://www.jstips.co/en/converting-truthy-falsy-values-to-boolean/ , there are Disqus comments and more people can see this

**Comment by loverajoel** [comment]
@boneskull seems @hakhag didn't see this

**Comment by zenopopovici** [comment]
Closing, as conversation was moved. If you have suggestions on improvements for a specific tip, please make a PR.

**Comment by boneskull** [comment]
Moved where?

**Comment by zenopopovici** [comment]
@boneskull here:  http://www.jstips.co/en/converting-truthy-falsy-values-to-boolean/

**Comment by boneskull** [comment]
Well, I commented on there (and other are in agreement with me), but nothing has changed.  How do we get a tip changed?  Or in this case, probably removed?
