### ISSUE TITLE
Adding Disqus for commenting

### ISSUE THREAD

**Issue by pertrai1** [loverajoel/jstips#199]
Would it be worth it to add Disqus for being able to comment on the tips? I had some issues with the Fibonnaci examples, and if there was a way to comment for feedback, that would be great.

**Comment by kurtextrem** [comment]
:+1: very good idea :)

**Comment by pertrai1** [comment]
@kurtextrem :-). I would be willing to implement if it it ok to do so

**Comment by loverajoel** [comment]
@pertrai1 there are Disqus comments in the site. 
![image](https://cloud.githubusercontent.com/assets/1700100/12702969/b00ad852-c815-11e5-8b6b-0a1375a9c33e.png)

let me know if not work for you

**Comment by pertrai1** [comment]
ah be done gone. Did not even see that. Thanks @loverajoel
