### ISSUE TITLE
[TODO] - Chinese version

### ISSUE THREAD

**Issue by loverajoel** [loverajoel/jstips#201]
- We need have a index for this language
- Translate contribution rules

**Comment by sjfkai** [comment]
Is the `index` what you said was tips title list? 
And , witch directory should I push these files ? In `zh_CN/` like `/zh_CN/CONTRIBUTING.md`?
I will translate soon.

**Comment by loverajoel** [comment]
I think that is better create a `CONTRIBUTING_zh_CN.md` file in the root

**Comment by loverajoel** [comment]
@sjfkai I have to make a hot fix https://github.com/loverajoel/jstips/commit/e357531a0ea914d77f7d5acd460173e571f7299c 

Seems be a bug in the update of jekyll by github:
https://github.com/jekyll/jekyll/issues/4433
https://github.com/jekyll/jekyll/issues/4442

I will revert this when find another solution

**Comment by zenopopovici** [comment]
This is fixed for now.
