### ISSUE TITLE
What are the relations between branches?

### ISSUE THREAD

**Issue by AlphaHasi** [loverajoel/jstips#208]
I checked out master some weeks ago, pulled every now and then. Now I forked a branch and wanted to add some changes I did with my earlier checked out branch and see that the (new) branch is completely different from master. And there are more, so one branch has 32 tips, the other 30, the master "only" 23. Is there a reason that these branches are all having there own life? To which branch should one contribute, as the master seems to be the most outdated one?

**Comment by AlphaHasi** [comment]
Ach, ok, now I see: gh-pages is "default". Still confused, but I will take this one from now on.

**Comment by loverajoel** [comment]
:+1:
