### ISSUE TITLE
#33 Range Tip text mistake

### ISSUE THREAD

**Issue by StevenACoffman** [loverajoel/jstips#215]
The text should clearly state that original range will yield an array from 0... **N-1**, and the second version will yield an array from 1...N.

For instance:

``` javascript
const rangeZeroToNMinusOne = (N) => Array.apply(null, { length: N }).map(Number.call, Number);
console.log(rangeZeroToNMinusOne(3)); //[ 0, 1, 2 ]

const rangeToN = (N) => Array.apply(null, {length: N}).map(function(val,index){
  return index+1;  
});
console.log(rangeToN(3)); //[ 1, 2, 3 ]
```

By the way, the second version is probably not quite as useful as a start and end version:

```
const rangeStartToEnd = (start, end) => Array.apply(null, { length: end - start + 1 }).map((_, index) => index + start);
console.log(rangeStartToEnd(3,6)); //[ 3, 4, 5, 6 ]
```

**Comment by loverajoel** [comment]
@SarjuHansaliya ping!

**Comment by SarjuHansaliya** [comment]
@StevenACoffman Thanks for pointing out.
@loverajoel Should I update a post and create pull request ?
