### ISSUE TITLE
#34 ES6's let

### ISSUE THREAD

**Issue by jupl** [loverajoel/jstips#216]
It would probably be good to note that with ES6 the `let` keyword is useful since it's block scoped unlike `var`. In fact the following would work as expected, and a transpiler like Babel can transform the code to something similar to the tip solution.

``` js
for(let i=0; i<5; i++) {
    setTimeout(function() {
        console.log(i);
    }, 1000);
}
```

**Comment by loverajoel** [comment]
@madmantalking ping!

**Comment by JakeRawr** [comment]
@jupl Nice, I was just about to write what you just wrote.

Also, @madmantalking for the second and third examples. I think you meant to `console.log(temp)` instead of `console.log(i)` and the result would be `4 4 4 4 4`

**Comment by shrynx** [comment]
@loverajoel @JakeRawr oh yes , damn, i did that mistake , i'll make the necessary changes for logging temp.
and also i'll incorporate solution using let as an alternative solution

**Comment by adaniloff** [comment]
Hi there,

The last part of this tip is wrong : 

``` javascript
for (let i=0; i<5; i++) {
    var temp = i;
    setTimeout(function(){
        console.log(temp); 
    }, 1000);
}  
//will display 4 4 4 4 4
```

It should be either : 

``` javascript
for (let i=0; i<5; i++) {
    setTimeout(function(){
        console.log(i); 
    }, 1000);
}   
```

Or : 

``` javascript
for (var i=0; i<5; i++) {
    let temp = i;
    setTimeout(function(){
        console.log(temp); 
    }, 1000);
}   
```

**Comment by zenopopovici** [comment]
@loverajoel: This should be closed as the PR for it is closed. We should add "Fixes #bugnumber" to our commit message so that when the PR is closed, also the afferent bug is closed.
