### ISSUE TITLE
Tip #35 Elaborate on ++ and --

### ISSUE THREAD

**Issue by ffigiel** [loverajoel/jstips#223]
Sorry to bash on this tip like that, but I think we could provide more details on ++ and -- operators. Maybe add a new section about them?

For example, what's the difference between `var b = --a;` and `var b = a--;`?

**Comment by timomeh** [comment]
Seeing that post I immediately thought that, too.

Knowing the difference between `a--` and `--a` is quite useful – especially in combination with ternary operators.

**Comment by hsleonis** [comment]
Yeah. `a--` and `--a` or `a++` and `++a` are quite interesting.

```
var a = 3;
var b = --a; // Now b is 2
```

And

```
var a = 3;
var b = a--; // Now b is 3
```

**Comment by zenopopovici** [comment]
@megapctr Could you create a new PR with the proposed changes? We'll merge once we review it.

Thanks.

**Comment by ffigiel** [comment]
You're welcome :wink:

**Comment by ffigiel** [comment]
I noticed that [jstips.co](http://www.jstips.co/en/assignment-shorthands/) doesn't render my ordered list properly (compare to [github](https://github.com/loverajoel/jstips/blob/gh-pages/_posts/en/2016-02-04-assignment-shorthands.md)). Should I open an issue for this?

**Comment by zenopopovici** [comment]
@loverajoel It seems that Jekyll is doing something fishy with the GitHub pages. Is this related to the warning we receive on each merge?

**Comment by loverajoel** [comment]
@zenopopovici @mebjas so strange, I think that maybe it's related with the Jekyll update in the last time for Github, I will back with more info.
Thanks
