### ISSUE TITLE
array average and median

### ISSUE THREAD

**Issue by lewisje** [loverajoel/jstips#236]
In the [example about getting the median of an array](https://github.com/loverajoel/jstips/blob/gh-pages/_posts/en/2016-02-10-array-average-and-median.md) you appear to get the higher of the two middle values, when sorting an array with an even number of values; usually, however, the median is defined as the arithmetic mean of the two middle values, and the following change will follow that definition:

``` javascript
let values = [2, 56, 3, 41, 0, 4, 100, 23];
values.sort((a, b) => a - b);
let lowMiddle = Math.floor((values.length - 1) / 2);
let highMiddle = Math.ceil((values.length - 1) / 2);
let median = (values[lowMiddle] + values[highMiddle]) / 2;
// median = 13.5
```

If the array has odd length, then `lowMiddle === highMiddle` so the median is still the middle value. Something similar could probably be done with the right-shift operator, but my first stab at it didn't work on arrays of odd length.

(Maybe you could use `let highMiddle = values.length >> 1;` and `let lowMiddle = highMiddle - (~values.length & 1);` to keep it using bitwise operators.)

**Comment by loverajoel** [comment]
@soyuka ping!

**Comment by soyuka** [comment]
Yes you're right, my mistake thanks!
