### ISSUE TITLE
#46 gross oversimplification

### ISSUE THREAD

**Issue by rjgotten** [loverajoel/jstips#249]
The code and instructions given in #46 are a gross oversimplification. Have a look at the hoops jQuery needs to jump through to arrive at a reliable cross-browser 'dom ready'.

(Perhaps it's time to start vetting tips before publishing them, because this is the umpteenth time that you're spreading wrong information and potentially harming other unknowing people's codebases with it.)

**Comment by kurtextrem** [comment]
:+1: totally correct!

**Comment by loverajoel** [comment]
@rjgotten I agree with you, even these days I have in mind rethink the "one js tip per day", following this directive, force us merge tips fast and without review enough.

**Comment by loverajoel** [comment]
@radibit @kurtextrem https://github.com/loverajoel/jstips/issues/251

**Comment by zenopopovici** [comment]
We're adding new rules in the coming days. #46 has been closed for now.
