### ISSUE TITLE
Misspelling in tip 35?

### ISSUE THREAD

**Issue by gcjbr** [loverajoel/jstips#256]
I'm contributing to the Portuguese translation, and I think I might have found a misspelling in tip 35, English version.

At like 17 it reads:

> This is the **similiar** use of

Is "similiar" a misspelling of "similar" or is it a technical term I'm not aware of?

**Comment by jklosinski** [comment]
It's a misspelling.

**Comment by sjfkai** [comment]
fixed by #258
