### ISSUE TITLE
Tip #00 Error

### ISSUE THREAD

**Issue by jeremyfourna** [loverajoel/jstips#257]
Via url of the tip : http://jsperf.com/push-item-inside-an-array

```
var arr = [1,2,3,4,5];

arr.push(6);
arr[arr.length] = 6; // 43% faster in Chrome 47.0.2526.106 on Mac OS X 10.11.1
```

It's false !

arr.push(6); does 26 457 551 operations per second ! in Chrome 47.0.2526.106
arr[arr.length] = 6; does 5 223 471 operations per second ! in Chrome 47.0.2526.106

READ : operations per second (higher is better) at the bottom of the chart !

So in fact arr.push(6); is 5.06 times faster !!! in Chrome 47.0.2526.106

Could you modify the tip please

**Comment by adaniloff** [comment]
@loverajoel :shipit:

**Comment by loverajoel** [comment]
@dexterneo you are right, can you send a PR? if not, let me know and I will made the fix

**Comment by jeremyfourna** [comment]
OK I'll send a PR during the WE

**Comment by drakmail** [comment]
Also, in safari `arr[arr.length] = 6;` is almost 2% faster that push :-)

**Comment by drakmail** [comment]
And maybe benchmark doesn't correct because there is could be some browser engine optimizations caused by same data in all tests (arr always have same set of elements)

**Comment by jeremyfourna** [comment]
Hope the PR will be of use.

**Comment by jeremyfourna** [comment]
I'll let you close the issue if the PR is OK with you.

**Comment by zenopopovici** [comment]
Cool stuff! Thanks @dexterneo, we'll add it under review this week.

**Comment by SudoKillMe** [comment]
`var arr1 = [];
var arr2 = [];
var arr3 = [];
var arr4 = [];`
`console.time(11);`
`for(var i=0; i<10; i++){`
`arr1.push(i);`
`}`
`console.timeEnd(11);//output: **0.437**ms`

`console.time(22);`
`for(var i=0; i<10; i++){`
    `arr2[arr2.length] = i;`
`}`
`console.timeEnd(22);
//output: **0.062**ms`

`console.time(33);`
`for(var i=0; i<100000000; i++){`
    `arr3.push(i);`
`}`
`console.timeEnd(33);
//output: **2127.292**ms`

`console.time(44);`
`for(var i=0; i<100000000; i++){`
    `arr4[arr4.length] = i;`
`}`
`console.timeEnd(44);
//output: **2224.373**ms`
i have tested too, and i found that if i is very small ,the second way  is faster
however,if i is large enough ，they almost have same speed,even the first way execute faster than the second
