### ISSUE TITLE
Tip #46 - Document ready

### ISSUE THREAD

**Issue by mathiasbynens** [loverajoel/jstips#262]
Re: https://github.com/loverajoel/jstips/blob/gh-pages/_posts/en/2016-02-15-detect-document-ready-in-pure-js.md

Why not just use the `DOMContentLoaded` event for those use cases?

**Comment by adaniloff** [comment]
I think it's more about (browsers') compatibilities, as explained [here](https://developer.mozilla.org/en-US/docs/Web/Events/readystatechange).

Not really sure about it though.

```
The readystatechange event is fired when the readyState attribute of a document has changed.
[ ... ] 
This event has long been supported by Internet Explorer and can be used as an alternative to the DOMContentLoaded event (see the cross-browser fallback section).
```

It may be helpful to add it in the tip @loverajoel :)

**Comment by mathiasbynens** [comment]
For old IE support you need something like https://github.com/dperini/ContentLoaded/blob/master/src/contentloaded.js anyway.

**Comment by adaniloff** [comment]
About [compatibilities](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded#Cross-browser_fallback) : 

```
[2] Internet Explorer 8 supports the readystatechange event, which can be used to detect when the DOM is ready. In earlier versions of Internet Explorer, this state can be detected by repeatedly trying to execute document.documentElement.doScroll("left");, as this snippet will throw an error until the DOM is ready.
```

So I guess it wont work for older versions than IE8, in which case `contentLoaded` would be required.

**Comment by mathiasbynens** [comment]
To summarize:
1. `DOMContentLoaded` is IE9+.
2. If you need to support IE8 and older (in 2016 I hope you don’t have to) you should use something like https://github.com/dperini/ContentLoaded/blob/master/src/contentloaded.js that implements the scrolling trick (which the code samples in this post don’t do).

IMHO the post should be simplified to use `DOMContentLoaded` for the last two examples. If IE8 support is a concern then https://github.com/dperini/ContentLoaded should be mentioned.

**Comment by adaniloff** [comment]
Seems legit :) :shipit: !

**Comment by loverajoel** [comment]
@madmantalking I can add one more case using this `DOMContentLoaded`, what do you think

Thanks for your suggestion

**Comment by zenopopovici** [comment]
I think IE9+ support is OK. Older browsers are simply edge cases which we shouldn't cover anymore.

**Comment by pastrop** [comment]
This one is probably should be closed.  I also think that we shouldn't worry about IE8 and earlier browsers.  In all fairness none of the newer JS capabilities are supported in older browsers and fewer and fewer people working on new systems care about those.  Sure, there are older systems that need to be maintained but if you are in the maintenance mode, you probably already know what to watch for so :shipit: for this one
