### ISSUE TITLE
Fix translation for #265

### ISSUE THREAD

**Issue by jonathanKingston** [loverajoel/jstips#266]
This changes the wording around security:
https://github.com/loverajoel/jstips/pull/265

**Comment by zenopopovici** [comment]
Changes accepted. Makes perfect sense.

**Comment by zenopopovici** [comment]
Forgot about Chinese. We'll need a process to do this.

**Comment by zenopopovici** [comment]
Update: Chinese language will be updated by the language responsible.

**Comment by jonathanKingston** [comment]
Thank you!
