### ISSUE TITLE
Tip #06 incorrect code for what it suggests

### ISSUE THREAD

**Issue by volcodc** [loverajoel/jstips#27]
Tip #06 suggests that it's code returns the first letter capital rather than the whole word.

_printUpperCase("cactus"); 
// => Cactus_

Ideally, if the end result wanted to look like that, the code should reflect something like this:

``` javascript
function printUpperCase(words) {
  var elements = [].concat(words); 
  for (var i = 0; i < elements.length; i++) {
    var tmpArr = elements[i].split(''),
        retVal = tmpArr.shift().toUpperCase() + tmpArr.join('');
    console.log(retVal);
  }
}
```

Just wanted to assist! Thanks!
-Chris

**Comment by loverajoel** [comment]
@mattfxyz ping here!

**Comment by mattfaluotico** [comment]
You're right Chris. This was the print every word in all uppercase.m. I incorrectly wrote the sample output.

**Comment by grav** [comment]
Consider `map`'ing a function over an array instead of changing each function to contain a `for`-loop

```
["foo","bar"].map(someFunction)
```

It is an ES5 feature: http://caniuse.com/#search=map

**Comment by Roland1975** [comment]
I'd rather avoid passing an array of items. Let the function proceed the arguments as an array using the native 'slice':

``` javascript
function printUpperCase(/* item1, item2, item n */) {
  var elements = Array.prototype.slice.call(arguments);
  //...
}
```

``` javascript
printUpperCase('item1', 'item2'); //ITEM1, ITEM2
```

An array is an object; if you keep it local inside the function, the browser will garbage it as soon as the function exits.

**Comment by kurtextrem** [comment]
That only works with use strict, else we leak arguments.

Roland notifications@github.com schrieb am Fr., 8. Jan. 2016 18:15:

**Comment by loverajoel** [comment]
Hey can we close this?

**Comment by zenopopovici** [comment]
Please submit changes in a PR and re-open this if you believe the tip is still not OK.
