### ISSUE TITLE
Tip33 Number.call ? 

### ISSUE THREAD

**Issue by SudoKillMe** [loverajoel/jstips#272]
Array.apply(null,{length:10}).map(Number.call,**Number**);
in tip33, if function map's second param is 'Array',the result will be nine arrays;if the second param is 'Object',the result will be something like '[number:0]'...I wonder **how the param influences the result**?
and what is the reference of 'this' in Number.call?
thank you

**Comment by rainbowcatcher** [comment]
Map's second param is used as `this` when executing callback,so `Array.apply(null,{length:10}).map(Number.call,Number)`  will execute `Number.call.call(Number,undefined, n)` in each loop.`Number.call.call(Number,undefined, n)` is the same as `Number.call(undefined, n)`.
You can also use `Array.apply(null,{length:10}).map(Function.prototype.call,[Number|Array|Object])` instead.

**Comment by SudoKillMe** [comment]
@kubrick1991 
Thank you very much. I benefited a lot from your answer.
however,I still have a question,as you said:
`Array.apply(null,{length:10}).map(Function.prototype.call,Number)` will execute `Function.prototype.call.call(Number,undefined,0,[undefined,...])` for the first element,in this code,'this' refers to 'Number'(am i right?),and this is the same as `Function.prototype.call(undefined,0,[undefined,...])`,in this code,'this' refers to 'undefined'(am i right?), so in my view,this code is the same as `Function(0)`,the result should have nothing with the second param([Number|Object|Array]),however,the second param influences the result,could you tell me why?
thank you again!

**Comment by rainbowcatcher** [comment]
@SudoKillMe 
`Function.prototype.call.call([Number|Array|Object],undefined,n)` is the same as `[Number|Array|Object].call(undefined,n)`,not `Function.prototype.call(undefined,n)`.The second param is the function to finally execute, and the first param is just a `call` function.

**Comment by moorsiek** [comment]
@SudoKillMe 
`Function.prototype.call(undefined,0)` is not the same as `Function(0)`.

The former calls function `Function.prototype` with `undefined` as its context and `0, [undefined, ...]` as its arguments. This will return `undefined` (function `Function.prototype` always returns `undefined`).

The latter calls constructor `Function` with only argument `0`. The result of such call is a newly created function with `0` used as it`s body, i.e. it`s almost the same as `function(){0}`.

The thing is `call` function calls some function in some context with some arguments. If you invoke "call" as member of some object (e.g. `Function.prototype.call(...`) then this object will be used as a function to be called.

**Comment by SudoKillMe** [comment]
@kubrick1991 
thanks a lot! I never thought the detail of these functions,you helped me a lot
thanks again

**Comment by SudoKillMe** [comment]
@schyzoo 
thanks,your answer made me understand something that I didn't know
