### ISSUE TITLE
What's happened?

### ISSUE THREAD

**Issue by woverton** [loverajoel/jstips#284]
Why have there not been any new tips since 48?

**Comment by FagnerMartinsBrack** [comment]
See #260.

@loverajoel, need to update the project description:

> This is about one JS tip every day!

**Comment by zenopopovici** [comment]
@woverton there are tips in review, you can contribute by giving your :shipit: (OK) vote to them or suggest improvements. Take a look at the open PRs.

**Comment by loverajoel** [comment]
@woverton how @zenopopovici said, rules changed, we are waiting for review for merge, for example this https://github.com/loverajoel/jstips/pull/248
