### ISSUE TITLE
JSTips Labels / Tags

### ISSUE THREAD

**Issue by pastrop** [loverajoel/jstips#287]
Overall thought about the selection criterion for JSTips: I think a priority should be given to the tips useful for practical development problems that JS developers are facing that are not well addressed in the existing resources.  Just to give a few examples:  Lately, I have been coding using MEAN stack.  There are a very few resources addressing issues associated with NPM Mongoose (MongoDB module for NodeJS) integration (i.e save() method is sporadically stops working, upsert option in findOneAndUpdate() has a new flag that has to be included if you want this method to work for new entries in to be added to the DB although this information is nowhere to be found in documentation.)  Another good example is from my recent experience with the front-end dev't: if you need to find out in JS which cell in the table is clicked on, you should be really attentive how you do it because this click events tend to fire multiple times on every click.  Again, good luck with searching for a solution for this.  It'll take you a while....Those are just examples.  I think this sort of tips are much more valuable than, say, discussions on  the way of using prototypical inheritance patterns.  Doug Crockford is a pretty good source for those.  So, except you can prove you are better better than Doug, read the book first and submit your tip later if you still think it is valuable....There is no point of covering issues that are well covered in the literature and/or are all over Stackoverflow.  Just my 2 cents.....

**Comment by calderaro** [comment]
L

**Comment by zenopopovici** [comment]
@pastrop Everybody is more than welcome to contribute with a PR. We're not refusing anything that is of interest.

**Comment by kurtextrem** [comment]
Your last few sentences clearly show the reason for JSTips: "All over the
place".
So who has time to go over every answer on StackOverflow? How do you Google
things you don't even know (e.g. as beginner: "wtf is prototype?". If you
don't know it, you can't find it).
Our tips aren't for pros only, but target beginners as well. If they want
to get better, they can find multiple good tips in one place, reviewed by
multiple good JS authors.
Of course we don't only target beginners, we'd like to have tips for
everyone.
We highly welcome any type of PR's!

**Comment by ro0NL** [comment]
Perhaps each tip should be indicated with some sort of level? i.e. `beginner`, `medior`, `pro`?

**Comment by zenopopovici** [comment]
@ro0NL Not a bad suggestion ... //cc @loverajoel

**Comment by loverajoel** [comment]
@ro0NL @zenopopovici yep, we can create labels or tags and I jekyll support this

**Comment by zenopopovici** [comment]
Merged with: https://github.com/loverajoel/jstips/issues/368
