### ISSUE TITLE
Tip 49 is not a unix timestamp...

### ISSUE THREAD

**Issue by tracker1** [loverajoel/jstips#293]
A unix timestamp is based in seconds since the UNIX epoc.   A JavaScript datetime value is the milliseconds.. you need to divide by 1000 to get a unix timestamp.

```
var dtm = new Date(); //or some other date instance
var timestamp = ~~(dtm / 1000)
```

**Comment by loverajoel** [comment]
@tracker1 true

@nmrony take a look here

**Comment by nurrony** [comment]
Yes true, silly mistake always gives pain. @tracker1 Thanks... @loverajoel Let me send a patch for it. How can I send a patch?

**Comment by kurtextrem** [comment]
Just do another PR.

**Comment by hingsir** [comment]
It seems that RFC2822 has much compatibility than ISO8601, so we prefer `new Date('2016/01/01')`  to `new Date('2016-01-01')`

**Comment by gromgit** [comment]
@hingsir RFC2822 dates are of the form "01 Jan 2016" rather than "2016/01/01", and RFC3339 (the official "Internet date and timestamps" RFC) is actually based on ISO8601, so I'm not sure what you mean by "compatibility".

**Comment by nmrony** [comment]
@hingsir JS dateString value is compatible with IETF-compliant RFC 2822 timestamps and also a version of ISO8601. You can easily find this comparing the return values of `new Date('2012-06-08').getTime()` and `new Date('2012/06/08').getTime()`.  For more information please see [Date Javascript MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

**Comment by nurrony** [comment]
@hingsir JS `dateString` value is compatible with IETF-compliant RFC 2822 timestamps and also a version of ISO8601. Main difference is between time zones 
please check 
-  [Date Javascript MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
- [Date.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)

**Comment by nurrony** [comment]
@loverajoel @kurtextrem Sent another PR with conversion in seconds #294

**Comment by hingsir** [comment]
@nmrony @gromgit You both right. The problem I met was that `new Date('2016-1-1')` returns  `Invalid Date` in iOS environment while `new Date('2016/1/1')` parsed correctly

**Comment by nurrony** [comment]
@hingsir yes  and to convert it into `ISO-8601` format you need to pass `YYYY-MM-DDT00:00:00Z` and it should works fine on iOS. I don't have iOS devices right now. Can you confirm it? Then I will add it in Tip #294. One more thing `ES5`  assumes timezone is `UTC` where `ES2015` will be  Local timezone

**Comment by gromgit** [comment]
@nmrony @hingsir Safari for iOS 9.2.1 handles ISO8601 `2016-01-01T00:00:00Z` just fine.

I also tested the other formats listed in the _Date and time (current at page generation) expressed according to ISO 8601_ sidebar of [https://en.wikipedia.org/wiki/ISO_8601](the Wikipedia page), across a slew of browsers on Linux, Mac OS X, iOS and Android. I was not surprised that every browser rejects the week-related date formats, but I was shocked that both `20160101T000000Z` and the ordinal date format `2016-001` also failed.

Clearly, code that handles textual dates **always** need to sanitize them beforehand.

**Comment by nurrony** [comment]
@gromgit I will update PR adding the information soon

**Comment by loverajoel** [comment]
fix merged
