### ISSUE TITLE
merge PR but page not change.

### ISSUE THREAD

**Issue by neighborhood999** [loverajoel/jstips#295]
Hey @loverajoel, I have a question.
I already merge my #286, but I go to jstips blog found article no update.
what's happen?

**Comment by sjfkai** [comment]
I have the same problem at zh_CN version. I have commited the newest tip but it not appears.
@loverajoel

**Comment by zenopopovici** [comment]
We have a build failure due to Jekyll changes for GitHub pages. @loverajoel needs to look into this.

```
The page build failed with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

 https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

If you have any questions you can contact us by replying to this email.
```

**Comment by zenopopovici** [comment]
Maybe #285 is also related to this?

**Comment by zenopopovici** [comment]
It seems that it was unrelated to GitHub changes, but due to @neighborhood999 changes. Please make sure titles do not start with a backtick, this will break jekyll. I've fixed this.

**Comment by neighborhood999** [comment]
@zenopopovici Sorry, it's my bad.
