### ISSUE TITLE
Tip #48 has confusing title

### ISSUE THREAD

**Issue by gromgit** [loverajoel/jstips#302]
I interpret **Reduce builtin function usage** as "cut down on your usage of native functions", which is a downright bizarre sentiment.

@darul75 I suggest a catchier and more accurate replacement: **How to `reduce()` and PROFIT!**

**Comment by loverajoel** [comment]
@darul75 what do you think about it?

**Comment by kurtextrem** [comment]
I think your proposed title is a bit too catchy, but I can definitely see why we should rename it.
Quick fix: adding backticks?

**Comment by gromgit** [comment]
Or perhaps a simple **How to `reduce()` arrays**?

**Comment by zenopopovici** [comment]
@gromgit PR please.

**Comment by darul75** [comment]
Hi all,

Sure it was a bit confusing and I did not know how to express it well.

I have to think about it too but if you have idea just put it I am on
holiday now and connexion very bad here.

Kindly,

Julien

Port: 06 24 79 14 83

2016-03-02 0:22 GMT+01:00 Zeno Popovici notifications@github.com:

**Comment by gromgit** [comment]
@zenopopovici Done, #308

**Comment by kurtextrem** [comment]
If @darul75 is fine with that :shipit: (#308)

2016-03-02 6:28 GMT+01:00 gromgit notifications@github.com:

**Comment by darul75** [comment]
Sounds good :+1:

**Comment by loverajoel** [comment]
merged!

Thanks all :+1:
