### ISSUE TITLE
Tips for other (programming) languages?

### ISSUE THREAD

**Issue by ro0NL** [loverajoel/jstips#310]
First of all, I like the idea of this repo :+1: just a nice read now and then.

However i was wondering.. perhaps we should do this for other (programming) languages too, i.e. gather any tip in any language. Allowing us to filter on language, or perhaps a tailored page per language (PHPTips, JSTips, etc.)

What do you think?

**Comment by zenopopovici** [comment]
Right now we would have to change a lot to implement this or start separate side-projects. I don't know the availablility of @loverajoel to do that. Or maybe you could start your own project :)

**Comment by ro0NL** [comment]
I understand. I'm not sure @loverajoel only fancies JS a lot or is willing to support multiple programming languages at all. If so I would like to help and think a uniform app with tips would be a huge +1 from my POV.

So we have a few choices here;
- Integrate multiple languages in the current app (JSTips becomes GenericTips basicly or just Tips ;-))
- A side project per language in a uniform way (JSTips, PHPTips), i.e. sharing the codebase of "the" app and 1 central github organization with tip repo's
- Every man for himself :)

**Comment by kurtextrem** [comment]
A "Tips" orga and for every repo one main maintainer (plus helpers) would
be ideal I'd say :D
Am 03.03.2016 12:21 schrieb "Roland Franssen" notifications@github.com:

**Comment by loverajoel** [comment]
Yep, it's a good idea, but take a lot of time maintain one single repo (js tips) I can't imagine how many time will take administrate more tips projects.

I think that we have to find people from others languages (python, php, c, ...) and try it.

**Comment by zenopopovici** [comment]
JS Tips for now. Is there are peple who want to fork this and become maintainers, let us know.
