### ISSUE TITLE
page build problem

### ISSUE THREAD

**Issue by neighborhood999** [loverajoel/jstips#312]
#295

![](http://imgur.com/4WAwR6t.png)

if **tip-tldr** start with (`), make build failure.

after fix:
![](http://imgur.com/Hx5u2WE.png)

so we need add this information to **CONTRIBUTING** for user.

**Comment by zenopopovici** [comment]
@neighborhood999 https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING.md
It's already added... We as contributors must be vigilant before performing merges also.

**Comment by loverajoel** [comment]
for some reason, the build is broken and don't are sending the alert email.
I merged a new tip and sent another fix and the page didn't rebuild.
Any ideas?

**Comment by loverajoel** [comment]
In local everything works as expected

**Comment by loverajoel** [comment]
done :p

**Comment by zenopopovici** [comment]
What was the issue?

**Comment by neighborhood999** [comment]
@zenopopovici I megred before I have check, but I don't know tip-tldr let page build broken...

![](http://i.imgur.com/64mC33c.png)
yesterday, I wording contributors_zh_TW but in **Use backticks..** display is not normal...
I have fix and send PR #315
I know I am collaborator but I think this need @loverajoel @zenopopovici review and check, thanks :smile:

**Comment by zenopopovici** [comment]
@neighborhood999 Thanks ... I merged the change ... it looked fine in code, I'll be more careful. 

Also please feel free to fix things if you see a problem. I think it's better for a problem to be fixes as soon as possible than to wait for someone to approve an obvious fix. 

We can easily revert stuff if we do mistakes.

**Comment by loverajoel** [comment]
I think that my problem was Github lag, now everything are working as expected!
