### ISSUE TITLE
Tips not refreshing on iOS app

### ISSUE THREAD

**Issue by tazcarper** [loverajoel/jstips#332]
On iPhone 6. V 9.2.1. None of the tips show up on the app. I check for updates and nothing happens. What else can I provide to help with this issue? Redownload the app?

**Comment by zenopopovici** [comment]
@tazcarper Can you try to reinstall the app?

**Comment by loverajoel** [comment]
@tazcarper we didn't make the iOs app, somebody with the RSS feed made that, and yes it's failing :(

**Comment by Satya5614** [comment]
@tazcarper there is  a bug which clears all tips. Reinstalling the app can help you for now. @loverajoel I promise I will release the next version of the app this week with bugs fixed. And as you suggested I am developing it in React-Native.

**Comment by zenopopovici** [comment]
This should be fixed at least partially by #350.
