### ISSUE TITLE
Tip #49 easier unix timestamp

### ISSUE THREAD

**Issue by ghost** [loverajoel/jstips#339]
Maybe an easier and faster way?

``` js
timestamp = (+new Date / 1000) | 0
```

Does anyone know if this would have any problems?

**Comment by FagnerMartinsBrack** [comment]
Is `timestamp = (+new Date / 1000) | 0` intended to be the same as `timestamp = ~~(+new Date / 1000)` which is intended to be the same as `Math.floor(+new Date / 1000)`? If yes, then it is worth pointing out the benefits of each one so that one can decide the tradeoffs.

**Comment by lnfnunes** [comment]
I've no cons about neither of the options, just the sintaxe verbosity...
In terms of performance, _Date.now()_ looks faster than _new Date_ in my tests.

**Comment by zenopopovici** [comment]
Leaving as it is right now. If you have a suggestion, please make a PR with addendum to the tip.
