### ISSUE TITLE
Tips should be retroactively edited to add Tip # to them.

### ISSUE THREAD

**Issue by philn5d** [loverajoel/jstips#364]
Looking for a specific tip number in source has an extra step since the source is referenced by date. Maybe add tip numbers to md file names so that it's easiest to find.

**Comment by zenopopovici** [comment]
@philn5d Had that same issue. Thing is we can't change URLs but we could add the tip number. PRs are welcome. /cc @loverajoel

**Comment by zenopopovici** [comment]
Moved to: https://github.com/loverajoel/jstips/issues/368
Makes sense, since we're editing all tips.
