### ISSUE TITLE
Adding JSBin retroactively to all Tips

### ISSUE THREAD

**Issue by zenopopovici** [loverajoel/jstips#368]
1. Maybe we should add JSBin retroactively to all tips under a JSBin account?
2. Should we implement labels too?

**Comment by loverajoel** [comment]
I/m not sure it's a hard work, a lot of languages and a lot of tips. what do you think?

**Comment by zenopopovici** [comment]
I think I can do some / all of the work. Should we create an account?

**Comment by loverajoel** [comment]
ok I can help. Let me know how we can divide that. You can do it with your account.

**Comment by zenopopovici** [comment]
Let me start the first PR. I think I can do it in the weekend.

**Comment by zenopopovici** [comment]
@loverajoel Should we implement labels too? See #287

**Comment by zenopopovici** [comment]
@loverajoel Sorry will have to push back to next weekend. I'm swamped.

**Comment by zenopopovici** [comment]
@loverajoel I've started this, but it's not as easy as it seems. Most tips must be changed in order to be run properly and display meaningful messages in the console.

#372

**Comment by zenopopovici** [comment]
@loverajoel Have a look and tell me if I'm doing something wrong...
