### ISSUE TITLE
JS tips on Slack

### ISSUE THREAD

**Issue by rahuldhawani** [loverajoel/jstips#375]
Just a thought. Providing these superb tips on Slack channel. Any views?

**Comment by zenopopovici** [comment]
You mean here: https://jstipscommunity.slack.com/ ?

We already have it, didn't have the time to create a registration form and link it to the API for new users to be created automatically. (Like here: https://levels.io/slack-typeform-auto-invite-sign-ups/)

If you want to help... any PR to do this would be greatly appreciated.

**Comment by benjamincharity** [comment]
@rahuldhawani if someone fixes the RSS feed (#379) you could just set up slack to send the RSS feed to a specific slack channel. I've done this at work for `dev_news` (posts anytime the feed gets a new item) and for `dev_releases` where we've subscribed to the releases feed for various open source projects we use.

**Comment by zenopopovici** [comment]
We've built this: https://jstips-slack.herokuapp.com 
However there's not much traffic.

**Comment by benjamincharity** [comment]
Because there is an email list, there will not be any RSS support?
