### ISSUE TITLE
RSS feed broken?

### ISSUE THREAD

**Issue by benjamincharity** [loverajoel/jstips#379]
We set up a `DevNews` slack channel at my work and added several RSS feeds to it which seemed to work fine for a while. I was noticing that we weren't getting any new tips from JSTips recently so I went to the RSS feed and it seems empty:

![google chrome - - screen shot sep 12 2016 10 02 42 am](https://cloud.githubusercontent.com/assets/270193/18438601/1a4fa290-78d0-11e6-9ab6-4cc9c5b369ed.png)

If this gets remedied, RSS is a viable solution for #375 also

**Comment by zenopopovici** [comment]
@loverajoel can we do something about this?

**Comment by zenopopovici** [comment]
Feed is now fixed.
