### ISSUE TITLE
The difference between "var a = function (args) {};" and "function a (args) {};"

### ISSUE THREAD

**Issue by LiuMengzhou** [loverajoel/jstips#387]
As title says, I want to know the difference. Hope someone can write a post.

**Comment by lnfnunes** [comment]
@LiuMengzhou, I'd write this but I've just realized there's already a [_hoisting topic_](https://github.com/loverajoel/jstips/blob/gh-pages/_posts/en/2016-01-11-hoisting.md) covering this subject.

Check it out the end of the example after the comment
```javascript
// Outputs: 'I did it!'
doSomethingElse();
.
.
.
```

**Comment by zenopopovici** [comment]
Stale. Closing.
