### ISSUE TITLE
Single item / array tip doesn't account for undefined values 

### ISSUE THREAD

**Issue by boneskull** [loverajoel/jstips#42]
Maybe better to

`value = [].concat(value || [])`

**Comment by boneskull** [comment]
Otherwise you get `[undefined]`

**Comment by Amberlamps** [comment]
Also, usually you do not execute functions to log values to the console, but rather to process data and return values. If I pass a string to a function, I expect a string as return value, or at least not an array. It usually messes up the workflow in which the function is executed. I liked to add something like:

```
return typeof arguments[0] === 'string' ? elements[0] : elements;
```

**Comment by BlaM** [comment]
@Amberlamps: About the return value: I prefer to get the same type of return value each time I call a function - not a string once and an array the next time. Seems to be personal preference, but I'd say most functions always have a constant return type.

**Comment by Amberlamps** [comment]
@BlaM: I agree. But when I use a third party library that converts strings to upper case, I find it weird to get an array when passing a string.

```
console.log(require('third-party-lib').upperCase("javascript"));
// => ["JAVASCRIPT"]
```

**Comment by BlaM** [comment]
@Amberlamps: Usually you wouldn't rely on a third party lib to uppercase strings - you would use String.toUpperCase() :yum:. But in the end it all comes down to the definition of the function. There is no right or wrong here - and returning uppercase is just an example.

**Comment by loverajoel** [comment]
Hey can we close this?

**Comment by boneskull** [comment]
My original comment was not addressed.  You guys went off on a tangent.  :smile:

**Comment by zenopopovici** [comment]
@boneskull if you have any improvements can you submit a new PR? Or let us know if this can be closed.
