### ISSUE TITLE
About the website of the Angular Slide background color and text color to hurt the eyes of the proposal

### ISSUE THREAD

**Issue by stuxt** [loverajoel/jstips#427]
About the website of the Angular Slide background color and text color to hurt the eyes of the proposal。

When I visit your website http://www.jstips.co/, Angular slide part of the red background with black words, so that the eyes are uncomfortable. The status quo is as follows:

![1506590805156](https://user-images.githubusercontent.com/4355192/30959711-94002e3c-a473-11e7-97ff-31c970ae4a9a.jpg)

I think when the background is red ， the text is set to white is better, as shown below:
![1506590889464](https://user-images.githubusercontent.com/4355192/30959730-a01d6216-a473-11e7-8ee7-c33e7d6aedbd.jpg)

**Comment by zenopopovici** [comment]
@stuxt PR requests are welcome.

**Comment by zenopopovici** [comment]
Closed due to inactivity.
