### ISSUE TITLE
Website Mobile

### ISSUE THREAD

**Issue by ronielramos** [loverajoel/jstips#433]
The menu is not hidden on mobile version
![Screenshot_20190607-104802330](https://user-images.githubusercontent.com/15123917/59108686-e7ec8e80-8911-11e9-8429-d4af0b33a1c0.png)

**Comment by dhbalaji** [comment]
Issue no longer occurring on mobile browsers. Kindly close the issue.

**Comment by zenopopovici** [comment]
Thank you!
