### ISSUE TITLE
#07 - Strict Mode

### ISSUE THREAD

**Issue by hnordt** [loverajoel/jstips#51]
Worth noting that Strict Mode is always on on ES6/ES2015 modules.

We don't need to add "use strict" for ES6/2015 modules.

**Comment by bojidar80** [comment]
[unins000.dat.txt](https://github.com/loverajoel/jstips/files/86533/unins000.dat.txt)

[unins000.dat.txt](https://github.com/loverajoel/jstips/files/86535/unins000.dat.txt)

**Comment by loverajoel** [comment]
Hey can we close this?

**Comment by hnordt** [comment]
Of course.
