### ISSUE TITLE
Tip #8

### ISSUE THREAD

**Issue by Roland1975** [loverajoel/jstips#53]
For the sake of clarity, I'd recommend to the verbose semantic:

``` javascript
Array.prototype.slice.call(nodelist);
```

**Comment by tevko** [comment]
@Roland1975 I'm not sure what advantage `Array.prototype.slice.call(nodelist)` has over `Array.apply(null, nodelist)`  

In fact, I'd argue that the apply method is cleaner, faster, and easier to understand than the slice method. 

Also, the slice method is more of a hack / trick, whereas apply is literally built to accept an Array-like value

**Comment by duzun** [comment]
`Array.apply` and `[].slice` are not equivalent and here are two most important differences:
1. `Array.apply` would make all cells own properties. 
   As a proof, run this:
   `(new Array(100)).map(function(i){console.log(i)})` - no output
   `Array.apply(null, new Array(100)).map(function(i){console.log(i)})` - outputs "undefined" 100 times
2. `[].slice` is much faster, and the bigger array, the slower first method gets (in my tests 4x).

Proof: [Spped test](https://duzun.me/playground/js_speed#c=%20b%20%3D%20Array.apply%28null%2C%20a%29%3B%0A%2F%2F%20b%20%3D%20slice.call%28a%29%3B&d&i=var%20a%20%3D%20Array.apply%28null%2C%20Array%2810000%29%29.map%28function%28v%2Ci%29%7Breturn%20i%7D%29%3B%0Avar%20b%3B%0Avar%20slice%20%3D%20%5B%5D.slice%3B&n=10000)

**Comment by Havvy** [comment]
Furthermore, if you had an array-like of a single element that is a number, Array.apply will give you an array with .length of that number. You don't have to worry about that with NodeList fortunately.

Also, if you are targeting ES6, then Array.of() is exactly what you're looking for.

**Comment by gmarketer** [comment]
If you targeting ES6, there are more methods available:
- `for...of` can iterate over `NodeList`:

``` javascript
const divNodeList = document.querySelectorAll('div');
for (let divNode of divNodeList) {
    console.log(divNode);
}
```
-  if you want forced conversion to array, you can use more beautiful `spread operator`:

``` javascript
const divNodeArray = [...divNodeList];
```

**Comment by duzun** [comment]
For ES5 `concat` is the best choice:

``` js
 var divNodeArray = [].concat(divNodeList);
```

It is faster then `[].slice`, but has equivalent effect.

**Comment by davidbgk** [comment]
@duzun my results for tests on your previous proof link are quite similar between `slice` and `concat`. How do you compare the two more accurately?

**Comment by duzun** [comment]
@davidbgk I just run the test several times and write down the execution times, then make an average.
I know this is not the best method to benchmark, but gives a quick idea of what works better.

I think a jsPerf would be more accurate.

**Comment by loverajoel** [comment]
Hey can we close this?

**Comment by zenopopovici** [comment]
Please re-open and submit changes if this is still not OK.
