### ISSUE TITLE
#05 - Differences between undefined and null

### ISSUE THREAD

**Issue by oagarcia** [loverajoel/jstips#54]
"undefined means a variable has not been declared"

A variable that has not been declared doesn't exists, so this statement is contradictory.
Hence, if you reference a variable that is not declared, it's value is not undefined as a reference error is thrown instead. (If you talk about referencing a non existing property of an object, that shouldn't be called a variable).

**Comment by loverajoel** [comment]
@bhaskarmelkani ping
