### ISSUE TITLE
Future goodness tips

### ISSUE THREAD

**Issue by 0xF013** [loverajoel/jstips#55]
I was thinking that it would be cool to add a section about the upcoming/transpiled stuff that can be used with the new es6/7 drafts. For example http://blog.jeremyfairbank.com/javascript/javascript-es7-function-bind-syntax/ has some stuff that would be nice for the very first tip 

```
const { map, filter } = Array.prototype;

nodeList::map( node => node.xxx )
```

**Comment by duzun** [comment]
+1
