### ISSUE TITLE
Create tips categories

### ISSUE THREAD

**Issue by denar90** [loverajoel/jstips#59]
Hi. This project is going to be really big. So, I've been thinking about categories. What if tips will be divided by categories like:
Plain JS
ES2015
Angular JS
React JS
etc..

It will be easier to find tips for your needs.
@loverajoel What do you think?

**Comment by kurtextrem** [comment]
https://github.com/loverajoel/jstips/issues/18 regarding framework tips

I guess another solution would be creating own repositories for these frameworks (and linking to them from here). 
Here and then some tips in the main repo (e.g. if no other tip has been found)

**Comment by denar90** [comment]
Will it be some organization like jstips and repos in there?

**Comment by loverajoel** [comment]
@denar90 in this issue https://github.com/loverajoel/jstips/issues/18 we talked about it.
We decide that the daily js tips will be only vanilla js and tips about frameworks, toolis and more will be like a bonus.
Now we are working in a beautiful template for [jekyll-now](https://github.com/barryclark/jekyll-now) and will be more easy to read and follow tips.

**Comment by denar90** [comment]
Cool. Got it. Do you need some help?
