### ISSUE TITLE
Tip #03 - Improve Nested Conditionals example should have vastly different functions to call

### ISSUE THREAD

**Issue by petetnt** [loverajoel/jstips#66]
The question of the tip is formatted as follows:

> How can we improve and make more efficient nested if statement in javascript.
> 
> ```
> if (color) {
>   if (color === 'black') {
>     printBlackBackground();
>   } else if (color === 'red') {
>     printRedBackground();
>   } else if (color === 'blue') {
>     printBlueBackground();
>   } else if (color === 'green') {
>     printGreenBackground();
>   } else {
>     printYellowBackground();
>   }
> }
> ```

With the given information (the if-clause and the function names), the most obvious choice would be _just to refactor the functions itself_

```
  printBackground(color);

  /**/

  function printBackground(color = "yellow") {
     // do something with the color, default being yellow
  }
```

which is a good tip in itself, but maybe not in the same vain the original #03 is. Obviously this isn't always possible (or feasible) with all of the cases, so the example could be / should be easily modified to something that looks more non-trivial :smile_cat:

**Comment by loverajoel** [comment]
@AlbertoFuente ping!

**Comment by yuvarajvemula** [comment]
Can we make use of functions ,for loop and if combination.. For if we provided with too much number of choices ? 
How about this dears ? :smile:

**Comment by yuvarajvemula** [comment]
Or can we use switch case ??

**Comment by zenopopovici** [comment]
A function would be the most obvious choice here. Switch can work too, but in this case it should be a function. 
@petetnt Can you add a PR that completes the example with a function as you suggested?

**Comment by petetnt** [comment]
Whoops @zenopopovici missed that @-mention and did see it until this was closed. I can scratch up a PR though now quickly :+1:
