### ISSUE TITLE
Best way to write class in javascirpt?

### ISSUE THREAD

**Issue by jknaresh** [loverajoel/jstips#68]
var debug = function(){console.log(arguments);};

``` javascript
Model 1:
function class1(){
    this.name="github1";
}
obj1 = new class1();
debug(obj1.name);
Model 2:
var class2 = function(){
    this.name= "github2";
}
obj2 = new class2();
debug(obj2.name);

Model 3:
function class3(){
    var _this = this;
    _this.name="github3";
}
obj3 = new class3();
debug(obj3.name);

Model 4:
var class4 = function (){
    var _this = this;
    _this.name="github4";
}
obj4 = new class4();
debug(obj4.name);
```

Please update if you feel any other format?
Make sure, If you prefer using prototype Why?

thnx.

**Comment by hingsir** [comment]
@jknaresh it's hard to read :)  you can format your snippet with markdown.

**Comment by Havvy** [comment]
This is ultimately bikeshedding.

If you have ES6 and like the `class` keyword, use that.

I prefer calling Object.create() in the "constructor" function instead of dealing with `new` and `this`. They don't buy me anything but they do confuse newbies (and people who don't want to figure out how `this` works), but Object.create() is mostly obvious.

**Comment by jknaresh** [comment]
@Havvy Can you give an reference URL?

**Comment by yuvarajvemula** [comment]
Es6 classes. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

``` javascript
Model 5: 
class class5 {
constructor (){
this.name="github5"
}
}
obj5 = new class5(); 
debug(obj5.name);
```

**Comment by indianakernick** [comment]
Use ES6 syntax. It's the standard. The old syntax is kind of confusing to new comers anyway.

**Comment by yuvarajvemula** [comment]
Please add es6 classes to first option.. Because they are new ,easy to use and clear

**Comment by yuvarajvemula** [comment]
Above models seems varients of same thing .. Not fair to use.  Confusing thing to newbies

**Comment by indianakernick** [comment]
@shivarajnaidu 👍

**Comment by baptistebriel** [comment]
Like @shivarajnaidu, this is what I use (ES6):

``` javascript
class Scroll {

    constructor(opt) {

        this.options = opt || {};
    }

    init() {}
}
```

``` javascript
class Parallax extends Scroll {

    constructor(opt) {

        super(opt);
    }

    init() {

        // always remember to call the super methods
        // for the extended class
        // super.init() is basically Scroll.prototype.init.call(this);
        super.init();
    }
}
```

And later on...

``` javascript
// just an object containing possible options
const options = {};

// create a new class based on the default one
const thing = new Scroll(options);

// or the extended one
const thing = new Parallax(options);
```

https://github.com/lukehoban/es6features#classes

**Comment by joseluisq** [comment]
The best way to write "classes" in javascript is avoid `class` keyword and constructors, instead you should prefer factory functions for that.

**Comment by indianakernick** [comment]
@joseluisq the class keyword is syntactical sugar over the existing prototype system. So when you use the clear and easy to understand class syntax you are still using the same prototype stuff. There is absolutely no advantage to using prototype syntax

**Comment by indianakernick** [comment]
Tell em @shivarajnaidu and @baptistebriel

**Comment by joseluisq** [comment]
@Kerndog73 yep, sorry it was corrected now. Also It should prefer Composition instead "Inheritance".

**Comment by yuvarajvemula** [comment]
Thanks for your support @Kerndog73  and @baptistebriel , we can make use of `Default parameters` feature to avoid  `this.options = opt || {};` in above code @baptistebriel 
**we can initialize function parameters using `default parameters` feature in es6**

``` javascript
class Scroll {

    constructor(opt={}) {

        this.options = opt;
    }

    init() {}
}
```

_**This is small enhancement**_ @baptistebriel 
[**See Default parameters in Mozilla Developer Network**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)

**Comment by yuvarajvemula** [comment]
_**Below article gives a great explanation about classes and the reason to use them instead of using old es5 hacks**_
**see here**
<br/>
[_**`Object-Oriented JavaScript — A Deep Dive into ES6 Classes`**_](http://www.sitepoint.com/object-oriented-javascript-deep-dive-es6-classes/)
and
[_**`ES6 Classes in MDN`**_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)

**Comment by baptistebriel** [comment]
Nice one, @shivarajnaidu :)
Thanks for the links!

**Comment by loverajoel** [comment]
Hey [this](https://medium.com/@dan_abramov/how-to-use-classes-and-sleep-at-night-9af8de78ccb4#.wqb6sannb) a good article about this
