### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by mnort9** [loverajoel/jstips#70]
In addition to Twitter, it would be nice to receive a tip in a daily email.

**Comment by michaelzoidl** [comment]
+1

**Comment by drakmail** [comment]
:+1:

**Comment by rocketinventor** [comment]
@mnort9 What is the twitter handle?

**Comment by mnort9** [comment]
@tips_js

**Comment by mnort9** [comment]
Might be able to use something simple like IFTTT:
https://ifttt.com/recipes/234075-new-tweet-by-specific-user-send-me-an-email

**Comment by rocketinventor** [comment]
I think a mailer should have the full tip text _plus_ a link to github, not just a link to github and a title.

**Comment by gangsthub** [comment]
+1

**Comment by qaraluch** [comment]
+1

**Comment by barryceelen** [comment]
+1

**Comment by FoxxMD** [comment]
+1

**Comment by drakmail** [comment]
I'm created a Mailchimp campaign for anyone who want to receive latest js tip every day.

You can sign up here: http://js2016.tips

**Comment by loverajoel** [comment]
@drakmail Wowww that's awesome and the domain too

**Comment by rocketinventor** [comment]
Nice, that is exactly what I was hoping for!

**Comment by habfast** [comment]
Also it would be incredible if there was an RSS feed :)

**Comment by loverajoel** [comment]
@habfast I'm working on this :+1:

**Comment by drakmail** [comment]
Thank you all for feedback, send first Daily JS Tip to 16 subscribers :)

**Comment by drakmail** [comment]
@habfast Mailchimp automatically creates RSS feed: http://us12.campaign-archive1.com/feed?u=91c81a54b7387a056b046a2ca&id=9551be788c , you could use it :)

**Comment by habfast** [comment]
Oh that's great, thanks! However the layout is quite broken in the feedbin webapp (but fine in reeder).

**Comment by rocketinventor** [comment]
@drakmail Mysteriously, I suddenly stopped receiving tip emails after February 18. An ideas why?

**Comment by kurtextrem** [comment]
We've switched from daily to "higher quality through reviews first" meaning
there won't be daily tips, but instead from time to time.
Am 04.03.2016 03:20 schrieb "Elliot Gerchak" notifications@github.com:

**Comment by drakmail** [comment]
@rocketinventor after switching from not a daily tips I got a small vacation :relaxed: Starting tomorrow I'll continue sending tips. But it will be sent according to new js tips policy, as @kurtextrem mentioned before.
