### ISSUE TITLE
Tip #14

### ISSUE THREAD

**Issue by gmarketer** [loverajoel/jstips#79]
> The stakes at risk if you inaccurately explain the => behavior for this are that you end up thinking things like, “arrow functions are just syntax sugar for function…” They clearly are not. Nor are they sugar for var self = this or .bind(this).

http://blog.getify.com/arrow-this/

**Comment by loverajoel** [comment]
@pklinger ping

**Comment by pklinger** [comment]
@gmarketer Thank you for the interesting hint. Could you please give concrete improvement tips? Or add another example that clarifies the issue better?

**Comment by qaraluch** [comment]
Very good tip, That's just tip, not PhD paper, after all. Some nuances always will be, I guess. Add link to a further reading.
