### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by joshbivens** [loverajoel/jstips#95]
I tried (and failed) to set up an index/toc. I couldn't get the link from my toc to link to the id of the tip. This would be a good feature.

**Comment by pertrai1** [comment]
@joshbivens I agree and have suggested a structure for how the tips are help inside of the repo to then be used with the likes of Jekyll. #101

**Comment by joshbivens** [comment]
Yes! That would be cool. Much better than one _long_ document.

**Comment by loverajoel** [comment]
@joshbivens hey now we have this [here](https://github.com/loverajoel/jstips#tips-list)

Thanks
