### ISSUE TITLE
Can we translate this everyday tip to Chinese?

### ISSUE THREAD

**Issue by kalasoo** [loverajoel/jstips#96]
There are many JS developers in China, and I, a tech discussion/sharing community host, want to help translate this great series of tips to a Chinese version.

Do we have any official guidelines for this?

**Comment by hueitan** [comment]
https://github.com/loverajoel/jstips/pull/78

**Comment by kalasoo** [comment]
@huei90 Thx

**Comment by kalasoo** [comment]
@huei90 it seems he hasn't started the work. We'll work on it asap

**Comment by fundon** [comment]
@kalasoo I have started with this. See https://github.com/fundon/jstips/blob/zh_CN/README-zh_CN.md.  

You can join this repo https://github.com/fundon/jstips. :)

**Comment by kalasoo** [comment]
@fundon Awesome, I will register a domain name to host a simple static website for this daily tip in two languages.

**Comment by fundon** [comment]
@kalasoo Cool! I added you to collaborators.

**Comment by kalasoo** [comment]
@fundon let's do it. Do you have a wechat account? u can add me: **kalasoo**

**Comment by loverajoel** [comment]
@kalasoo I'm working in a jekyllrb blog and I think that it will be done for this week

**Comment by kalasoo** [comment]
@loverajoel cool, we'll keep it simple and tidy to different language versions.

**Comment by loverajoel** [comment]
@kalasoo @fundon  I have in mind host all languages in the same site, just looking how to make jekyllrb multi-language.
Maybe I can add how collaborator one person by idiom in order to help me administer the project

**Comment by kalasoo** [comment]
@loverajoel There's no problem hosting it in the same site. As I have registered jstips.cn already, we can host it separately but mutually linked.

**Comment by kalasoo** [comment]
@loverajoel Of course, the content should synced with the main site.

**Comment by loverajoel** [comment]
@kalasoo Do you have in mind how to organice the repo in two languages or more? 
These are options:
https://github.com/octopress/multilingual
https://github.com/drallgood/jekyll-multilingual

**Comment by loverajoel** [comment]
This one is good https://www.sylvaindurand.org/making-jekyll-multilingual/

**Comment by kalasoo** [comment]
@loverajoel I haven't used Jekyll before (#GhostLover), so I may need to learn it as well.

**Comment by FagnerMartinsBrack** [comment]
Now that you mentioned it, I am willing to translate these tips to portuguese from Brazil in case nobody have done it yet. Just document the patterns on how to do it :)

**Comment by LiYongSheldon** [comment]
@kalasoo It shouldn't be an issue as long as someone is willing to do it. However I assume the English is relatively simple here.

**Comment by loverajoel** [comment]
@FagnerMartinsBrack good idea, at the end of the week I will have the theme and basic structure that support multi-language done, I will back here with more info

**Comment by kalasoo** [comment]
@LiYongSheldon agree. Basically, it's more important to publish the content with a website & newsletter to help people approach it easily. Also, keep the credit to the contributors.

**Comment by FagnerMartinsBrack** [comment]
@loverajoel Looking forward to it :)

**Comment by frikinside** [comment]
I really love this repo and it would be awesome to world spread it in most of the common idioms!
Maybe I can give you a hand with Spanish translate?

**Comment by drakmail** [comment]
I could help to translate it to Russian :)

**Comment by loverajoel** [comment]
@frikinside @drakmail +1

**Comment by LorenzoRogai** [comment]
I can help with the Italian translation. Let me know when you have a structure to do so :+1:

**Comment by loverajoel** [comment]
@loonies in order to start, create a folder for you language (`en`,  `es`,  `cn`, `it`) and start to translate every tip, meanwhile I will adapt the theme

**Comment by loonies** [comment]
@LorenzoRogai, @loverajoel is probably replying to you

**Comment by LorenzoRogai** [comment]
@loverajoel @loonies I'm working on it
